title: Abhay Venkatesh
description: "Abhay Venkatesh is an engineer and researcher, early at Anduril, where he co-invented Lattice for Mission Autonomy and helped start its frontier AI initiative."
url: https://abhayvenkatesh.com
author: "Abhay Venkatesh"

markdown: kramdown

include:
    - _pages
    - .well-known

exclude:
    - .gitignore
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
