title: Abhay Venkatesh
description: Profile
author: "Abhay Venkatesh"

theme: minima

header_pages:
  - _pages/about.md
  - _pages/posts.md
  - _pages/projects.md

include:
    - _pages
    - .well-known


exclude: 
    - .gitignore
    - Gemfile
    - Gemfile.lock
    - LICENSE
