title: Abhay Venkatesh
description: Profile
author: "Abhay Venkatesh"

theme: minima

# Minima social links
twitter_username: abhayvenkatesh1
linkedin_username: abhayvenkatesh

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/about.md
  - _pages/frontpage.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md