title: abhay-venkatesh
author:
  name: abhay-venkatesh
  email: abhay.venkatesh@gmail.com

show_excerpts: true

minima:
  date_format: "%b %-d, %Y"
  social_links:
    twitter: abhayvenkatesh1
    github:  abhay-venkatesh
    linkedin: abhayvenkatesh
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
