title: Abhay Venkatesh
description: Profile
author: "Abhay Venkatesh"

theme: minima

header_pages:
  - _pages/about.md

include:
    - _pages
include: [".well-known"]



exclude: 
    - .gitignore
    - Gemfile
    - Gemfile.lock
    - LICENSE
