title: Abhay Venkatesh
description: Profile
author: "Abhay Venkatesh"

theme: minima

header_pages:
  - _pages/about.md
  - _pages/posts.md

include:
    - _pages

exclude: 
    - .gitignore
    - Gemfile
    - Gemfile.lock
    - LICENSE