title: Abhay Venkatesh
description: Profile
author: "Abhay Venkatesh"

markdown: kramdown

include:
    - _pages
    - .well-known

exclude:
    - .gitignore
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
