title: Abhay Venkatesh
description: "Abhay Venkatesh was an early ML engineer at Anduril and is now an angel investor."
url: https://abhayvenkatesh.com
author: "Abhay Venkatesh"

markdown: kramdown

include:
    - _pages
    - .well-known

exclude:
    - .gitignore
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
